// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mocvlvjlhtvnxtjhctin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vY3ZsdmpsaHR2bnh0amhjdGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MjgzMTYsImV4cCI6MjA2OTEwNDMxNn0.p-T4rY2NtjK_ZJy4VHYxSlTAZto_hSbTQg3pZs_R8uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});